app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^cart/$',views.cart,name='cart'),
    url(r'^detail/$',views.detail,name='detail'),
    url(r'^register/$',views.register,name='register'),
    url(r'^login/$',views.login,name='login'),
    url(r'^detail02/(\d+)/$',views.detail02,name='detail02'),
    url(r'^detail03/$',views.detail03,name='detail03'),
    url(r'^checkemail/$', views.checkemail, name=
        'checkemail'),
    url(r'^middle/$',views.middle,name='middle'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^show/$',views.show,name='show'),
    url(r'^addcart/$',views.addcart,name='addcart')

]

mybuy_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mybuy/',include('app.urls',namespace='mt'))
]

app/models.py
from django.db import models

# Create your models here.
#商品类
class Items(models.Model):
    name = models.CharField(max_length=150)
    price = models.FloatField(max_length=20)
    unit = models.CharField(max_length=10)
    headImg = models.CharField(max_length=200)
    zoom = models.CharField(max_length=1000)
    small = models.CharField(max_length=1000)

    class Meta:
        db_table = 'mybuy_items'


#用户模型类
class User(models.Model):
    email = models.CharField(max_length=100,unique=True)
    password = models.CharField(max_length=50)
    name = models.CharField(max_length=40)
    phone = models.CharField(max_length=20)

    token = models.CharField(max_length=256)

    class Meta:
        db_table = 'my_user'



class Cart(models.Model):
    # 用户
    user = models.ForeignKey(User)
    # 商品
    goods = models.ForeignKey(Items)
    # 商品个数
    number = models.IntegerField()
    # 是否选中
    isselect = models.BooleanField(default=True)


    class Meta:
        db_table = 'my_cart'

app/views.py
import hashlib
import random
import time

from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from app import models
from app.models import Items, User, Cart


def index(request):
    # 读取json文件 写入数据库
    # with open('/home/chenpeng/Desktop/mybuy_app/static/json/items.json','r',encoding='utf8') as qf:
    #     contents = qf.read()
    #     contents = eval(contents)
    #     for dict in contents:
    #         items = Items()
    #         items.headImg = dict['headImg']
    #         items.name = dict['name']
    #         items.unit = dict['unit']
    #         items.price = dict['price']
    #         items.save()
    items = Items.objects.all()

    token = request.session.get('token')


    data = {}
    data = {
        "items": items
    }
    if token:
        user = User.objects.get(token=token)
        data['name'] = user.name
        data['phone'] = user.phone
        data['email'] = user.email


    print(items.first().headImg)
    return render(request,'index/index.html',context=data)


# def cart(request):
#     return render(request,'cart/cart.html')

def cart(request):
    token = request.session.get('token')
    print(token)

    if token:
        user = User.objects.get(token=token)
        carts = Cart.objects.filter(user=user).exclude(number=0)

        data = {
            'carts': carts
        }

        return render(request, 'cart/cart.html', context=data)
    else:
        return redirect('mt:login')
    #     ids = request.GET.get('itemsid')
    #     sum = request.GET.get('sum')
    #     data = {}
    #     data['ids'] = ids
    #     data['sum'] = sum
    # #     goods = Items.objects.get(id=id)
    #     return render(request,'cart/cart.html',context=data)





def detail(request):
    # items = Items.objects.filter(pk=id).first()
    items = Items.objects.all()

    data = {
        "items": items
    }
    return render(request,'detail/detail.html',context=data)


def generate_password(param):
    md5 = hashlib.md5()
    md5.update(param.encode('utf-8'))
    return md5.hexdigest()


def generate_token():
    md5 = hashlib.md5()
    temp = str(time.time()) + str(random.random())
    md5.update(temp.encode('utf-8'))
    return md5.hexdigest()


def register(request):
    if request.method == 'GET':
        return render(request, 'register/register.html')
    elif request.method == 'POST':
        user = User()
        user.email = request.POST.get('email')
        user.password = generate_password(request.POST.get('password'))
        user.name = request.POST.get('name')
        user.phone = request.POST.get('phone')

        # 状态保持
        user.token = generate_token()
        user.save()
        request.session['token'] = user.token

        return redirect('mt:middle')
    
    


def login(request):
    if request.method == 'GET':
        return render(request, 'login/login.html')
    elif request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        print(generate_password(password))

        try:
            # 不存在，会抛出异常
            # 多个时，会抛出异常　【email是唯一约束】
            user = User.objects.get(email=email)
            if user.password == generate_password(password):
                user.token = generate_token()
                user.save()
                request.session['token'] = user.token
                return redirect('mt:index')
            else:
                return render(request, 'login/login.html', context={'p_err': '密码错误'})
        except:
            return render(request, 'login/login.html', context={'u_err': '账号不存在'})


def detail02(request,id):
    items = Items.objects.get(pk=id)



    token = request.session.get('token')



    data = {
        "items": items
    }
    return render(request,'detail/detail02.html',context=data)


def detail03(request):
    return render(request,'detail/detail03.html')


def checkemail(request):
    email = request.GET.get('email')

    users = User.objects.filter(email=email)
    if users.exists():
        return JsonResponse({'msg': '账号已被占用!', 'status': 0})
    else:
        return JsonResponse({'msg': '账号是可以使用!', 'status': 1})


def middle(request):
    return render(request,'register/middle.html')


def logout(request):
    request.session.flush()
    return redirect('mt:index')


def show(request):      #添加数据
    obj = models.Items.objects.get(price=699)
    obj.zoom = ["img/detailimg/common4-01.jpg"]
    obj.save()
    return HttpResponse('hao le')


def addcart(request):
    # 获取token  >> user
    token = request.session.get('token')

    # 获取商品id
    goodsid = request.GET.get('itemsid')
    sum = request.GET.get('sum')
    print(goodsid,sum)

    data = {}

    if token:  # 登录
        # 获取用户
        user = User.objects.get(token=token)
        # 获取商品
        goods = Items.objects.get(pk=goodsid)

        # 1、 第一次添加的商品是不存在的，要往数据库中添加一条新记录
        # 2、 商品已存在，即修改商品数量

        # 判断需要添加的商品是否存在
        carts = Cart.objects.filter(user=user).filter(goods=goods)
        if carts.exists():  # 存在
            cart = carts.first()
            cart.number = cart.number + int(sum)
            cart.save()
        else:  # 不存在
            cart = Cart()
            cart.user = user
            cart.goods = goods
            cart.number = sum
            cart.save()

        return JsonResponse({'msg': '{},添加购物车成功'.format(goods.name), 'number': cart.number, 'status': 1})

    else:  # 没登录
        # ajax操作中，不能重定向
        # ajax异步请求操作，数据的传输
        # 即ajax请求，如果想页面跳转(服务器重定向不了)，客户端处理
        # return redirect('axf:login')
        data['msg'] = '请登录后操作!'
        data['status'] = -1
        return JsonResponse(data)

templates/cart/cart.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>我的购物车_我买网</title>
		<script src="{% static 'cart/js/jquery-1.12.3.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'cart/js/jquery.cookie.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'cart/js/cart.js' %}" type="text/javascript" charset="utf-8"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'cart/css/reset.css' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'cart/css/cart.css' %}"/>
        <link rel="stylesheet" href="{% static 'cart/css/my.css' %}">
	</head>
	<body>
		<div class="cart-content">
			<div class="header">
				<div class="w">
					<ul class="nav-r">
						<li class="mycount-wrap">
							<a href="#">我的账户</a>
							<i></i>
							<div class="mycount">
								<dl class="count-l">
									<dt>您还没有登录</dt>
									<dd class="nopay"><a href="#"> 待付款订单</a><i></i></dd>
									<dd><a href="#"> 待签收订单</a></dd>
									<dd><a href="#"> 支付卡账户</a></dd>
									<dd><a href="#"> 优惠券/团购卡</a></dd>
									<dd><a href="#"> 电子礼品卡</a></dd>										    
								</dl>
								<dl class="count-r">
									<dt><span><a class="log" href="#">登录</a></span></dt>
									<dd class="mymsg"><a href="#"> 我的消息</a><i></i></dd>
									<dd><a href="#"> 我的订单</a></dd>
									<dd><a href="#"> 我的积分</a></dd>
									<dd><a href="#"> 我的收藏</a></dd>
								</dl>								
							</div>
						</li>
					</ul>
					<ul class="top-login">
						<li class="none"><span><a class="log" href="{% url 'mt:index' %}">首页</a></span></li>
						<li class="none">|<a class="reg" style="margin-left: 14px;" href="#"></a></li>
					</ul>
				</div>				
			</div>
			<div cl8ass="header-box w">
				<div class="logo">

					<a href="#"><img src={% static 'register/img/registerimg/logo.jpg' %}/></a>
				</div>
				<ul class="step">
					<li></li>
				</ul>
			</div>
            <div>
{#                <ul>#}
{#                    {% for good in carts %}#}
{#                        <li>#}
{#                            <img src="/static/{{ good.goods.headImg }}" alt="">#}
{#                        </li>#}
{#                    {% endfor %}#}
{#                    #}
{#                </ul>#}
               <div id="mycart">
                   <ul>
{#                       {% for cart in carts %}#}
{#                           <li class="goods">#}
{#                               <div class="confirm-wrapper" cartid="{{ cart.id }}">#}
{#                                   {% if cart.isselect %}#}
{#                                       <span class="glyphicon glyphicon-ok"></span>#}
{#                                   {% else %}#}
{#                                       <span class="no"></span>#}
{#                                   {% endif %}#}
{#                               </div>#}
{#                               <div class="content-wrapper">#}
{#                                   <div class="img">#}
{#                                       <img src="{{ cart.goods.headImg }}" alt="">#}
{#                                   </div>#}
{#                                   <div class="detail">#}
{#                                       <p class="name">{{ cart.goods.name }}</p>#}
{#                                       <p class="price" price="{{ cart.goods.price }}"> ￥ {{ cart.goods.price }}</p>#}
{#                                       <p class="num" num="{{ cart.number }}">x{{ cart.number }}</p>#}
{#                                   </div>#}
{#                               </div>#}
{#                           </li>#}
{#                       {% endfor %}#}
                       {% for cart in carts %}
                            <div class="goods">
                                <div class="img">
                                    <img src="/static/{{ cart.goods.headImg }}" alt="">
                                    <div class="cartplus">
                                         <ul class="btn-numbox">
                        <li><span class="number">数量</span></li>
                        <li>
                            <ul class="count" id="cartsum">
                                <li><span id="num-jian" class="num-jian" >-</span></li>
                                <li><input type="text" class="input-num" id="input-num" value="{{ cart.number }}"/></li>
                                <li><span id="num-jia" class="num-jia">+</span></li>
                            </ul>
                            <script>
                            　var num_jia = document.getElementById("num-jia");
                        var num_jian = document.getElementById("num-jian");
                        var input_num = document.getElementById("input-num");

                        num_jia.onclick = function() {

                        input_num.value = parseInt(input_num.value) + 1;
                        }

                        num_jian.onclick = function() {

                        if(input_num.value <= 0) {
                        input_num.value = 0;
                        } else {

                        input_num.value = parseInt(input_num.value) - 1;
                        }

                        }　
                        </script>
                        </li>

                        　
                        <script>
                            　var num_jia = document.getElementById("num-jia");
                        var num_jian = document.getElementById("num-jian");
                        var input_num = document.getElementById("input-num");

                        num_jia.onclick = function() {

                        input_num.value = parseInt(input_num.value) + 1;
                        }

                        num_jian.onclick = function() {

                        if(input_num.value <= 0) {
                        input_num.value = 0;
                        } else {

                        input_num.value = parseInt(input_num.value) - 1;
                        }

                        }　
                        </script>
                    </ul>
                                    </div>
                                </div>
                                <div class="detail">
                                    <p class="name">单价:  ￥ {{ cart.goods.price }}</p>
                                    <p class="num1">数量: x{{ cart.number }}</p>
                                </div>

                            </div>
                       {% endfor %}

                   </ul>
               </div>
            </div>
		</div>
		<div class="feeter w">
			<div class="beian">
				<p>
					<a href="#"><img src={% static 'register/img/registerimg/beian.png' %}/>京公网安备 11010102000458号</a>
					<span>|</span>
					京ICP备 13003995号 
					<span>|</span>
					营业执照（统一社会信用代码）91110000055590239L
					<span>|</span>
					食品经营许可证：JY11105020028185
				</p>
				<p class="bottom">Copyright©2009-2017 womai.com.hk 版权所有</p>
			</div>
		</div>
	</body>
</html>

templates/login/login.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>会员登录_我买网</title>
		<script src="{% static 'login/js/jquery-1.12.3.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'login/js/jquery.cookie.js' %}" type="text/javascript" charset="utf-8"></script>
        <script src="{% static 'register/js/bootstrap.min.js' %}"></script>
		<script src="{% static 'login/js/login.js' %}" type="text/javascript" charset="utf-8"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'login/css/reset.css' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'login/css/Login.css' %}"/>
        <link rel="stylesheet" href="{% static 'register/css/bootstrap.min.css' %}">
	</head>
	<body>
		<div class="content-wrap">		
			<div class="header">
				<div class="header-logo">
					<a href="#"><img src="{% static 'register/img/registerimg/logo.jpg' %}"/></a>
				</div>
				<div class="line">					
				</div>
			</div>
<!--			头部结束-->
			<div class="main">
				<div class="main-bg">
					<a href="#"><img src="{% static 'login/img/Loginimg/bgimg.jpg' %}"/></a>
				</div>			
				<div class="login-wrap">
					<div class="login-outside">
						<div class="login-inside">
							<h3>请登录中粮我买网</h3>
							<form action="{% url 'mt:login' %}" method="post" id="login-view">
                                {% csrf_token %}
                                <div class="form-group has-feedback" id="email">
                                    <input type="text" class="form-control" aria-describedby="inputSuccess2Status"
                                           placeholder="邮箱" name="email">
                                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                    <p>
                                        {{ u_err }}
                                    </p>
                                </div>

                                {#             密码#}
                                <div class="form-group has-feedback" id="password">
                                    <input type="password" class="form-control" aria-describedby="inputSuccess2Status"
                                           placeholder="密码" name="password">
                                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                    <p>
                                        {{ p_err }}
                                    </p>
                                </div>

                                <input type="submit" value="登录" id="subButton" disabled="disabled">
								<div class="friend">
									<h3>使用合作伙伴账号登录我买网</h3>
									<ul class="friend-links">
										<li><em></em><a href="#">QQ</a></li>
										<li><em></em><a href="#">人人网</a></li>
										<li><em></em><a href="#">开心网</a></li>
										<li><em></em><a href="#">支付宝</a></li>
										<li><em></em><a href="#">新浪微博</a></li>
										<li><em></em><a href="#">百度</a></li>
										<li><em></em><a href="#">建行</a></li>
										<li><em></em><a href="#">什么值得买</a></li>
										<li><em></em><a href="#">中英人寿</a></li>										
									</ul>
								</div>
								
							</form>
						</div>
					</div>
				</div>

			</div>

		</div>
		<ul class="feeter">
			<li>
				Copyright©2009-2017 womai.com.hk All Rights Reserved 中粮海优（北京）有限公司版权所有<br />
				中粮海优（北京）有限公司 北京市朝阳区朝阳门南大街8号18F-09室<br />
				<p>
					<a href="#"><img src="{% static 'register/img/registerimg/beian.png' %}"/><b>京公网安备 11010102000458号</b></a>
				</p>
				<span>京ICP备 13003995号 营业执照（统一社会信用代码）91110000055590239L 食品经营许可证（社会信用代码）05559023-9</span>
				
			</li>
			<li class="color"></li>
		</ul>
	</body>
</html>

templates/register/middle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>注册成功 <a href="{% url 'mt:login' %}">点击跳转登录</a></p>
</body>
</html>

templates/register/register.html
{% load static %}
{#<!DOCTYPE html>#}
<html>
	<head>
		<meta charset="UTF-8">
		<title>填写信息_会员注册</title>

        <script src="{% static 'register/js/jquery-1.12.3.js' %}" type="text/javascript" charset="utf-8"></script>
        <script src="{% static 'register/js/bootstrap.min.js' %}"></script>
		<script src="{% static 'register/js/jquery.cookie.js' %}" type="text/javascript" charset="utf-8"></script>
        <script src="{% static 'register/js/register.js' %}" type="text/javascript" charset="utf-8"></script>
        <script src="{% static 'register/js/my_register.js' %}"></script>

        <link rel="stylesheet" type="text/css" href="{% static 'register/css/reset.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'register/css/register.css' %}"/>
        <link rel="stylesheet" href="{% static 'register/css/bootstrap.min.css' %}">
        {#        <link rel="stylesheet" href="{% static 'register/css/bootstrap.min.css.map' %}">#}
    </head>
	<body>
		<div class="content-wrap">		
			<div class="header">
				<div class="header-logo">
					<a href="#"><img src="{% static 'register/img/registerimg/logo.jpg' %}"/></a>
				</div>
				<div class="line">					
				</div>
			</div>
<!--			头部结束-->
			<div class="main-wrap">
				<div class="main">
					<div class="main-out">
						<div class="main-inst">
						<div class="main-tit">
							注册我买网
							<p>已有我买网账号？<a href="#">登录</a></p>
							</div>
{#							<div class="main-cont">#}
{#								<form>#}
{#									<div class="long-input">#}
{#										<input type="text"/>#}
{#										<label class="msg">邮箱/手机</label>#}
{#										<div class="error-msg">#}
{#											<p></p>#}
{#										</div>#}
{#									</div>#}
{#									<div class="long-input">#}
{#										<input type="text"/>#}
{#										<label class="msg">用户名</label>#}
{#										<div class="error-msg">#}
{#											<p></p>#}
{#										</div>#}
{#									</div>#}
{#									<div class="long-input">#}
{#										<input type="password"/>#}
{#										<label class="msg">密码</label>#}
{#										<div class="error-msg">#}
{#											<p></p>#}
{#										</div>#}
{#									</div>#}
{#									<div class="long-input">#}
{#										<input type="password"/>#}
{#										<label class="msg">确认密码</label>#}
{#										<div class="error-msg">#}
{#											<p></p>#}
{#										</div>#}
{#									</div>#}
{#									<div class="long-input">#}
{#										<input type="text"/>#}
{#										<label class="msg">填写手机号</label>#}
{#										<div class="error-msg">#}
{#											<p></p>#}
{#										</div>#}
{#									</div>#}
{#									<div class="long-input">#}
{#										<input type="text" class="short"/>#}
{#										<label class="msg">手机验证码</label>#}
{#										<p class="phone" >发送验证码</p>#}
{#										<div class="error-msg">#}
{#											<p></p>#}
{#										</div>#}
{#									</div>#}
{#									<div class="clause-wrap clearfix">#}
{#										<div class="clause">#}
{#											<input type="checkbox" name="" id="" value="" />#}
{#											<a href="#">我已阅读并同意《我买网网上商城服务条款》</a>#}
{#											<div class="error-msg">#}
{#												<p></p>#}
{#											</div>#}
{#										</div>#}
{#									</div>#}
{#									<div class="refer-btn">#}
{#										<input type="button" name="" id="" value="立即注册" />#}
{#										<span>#}
{#											我有邀请码#}
{#										</span>#}
{#									</div>#}
{#								</form>#}
{##}
{#                                <form action="{% url 'mt:register' %}" method="post">#}
{##}
{#                                    邮箱#}
{#                                    <div class="form-group has-success has-feedback">#}
{#                                        <label class="control-label" for="inputSuccess2">Input with success</label>#}
{#                                        <input type="text" class="form-control" id="inputSuccess2"#}
{#                                               aria-describedby="inputSuccess2Status">#}
{#                                        <span class="glyphicon glyphicon-ok form-control-feedback"#}
{#                                              aria-hidden="true"></span>#}
{#                                        <span id="inputSuccess2Status" class="sr-only">(success)</span>#}
{#                                    </div>#}
{#                                    <p>#}
{#                                    <div class="form-group has-success">#}
{#                                        <label class="control-label" for="inputSuccess1">Input with success</label>#}
{#                                        <input type="text" class="form-control" id="inputSuccess1"#}
{#                                               aria-describedby="helpBlock2">#}
{#                                        <span id="helpBlock2" class="help-block">A block of help text that breaks onto a new line and may extend beyond one line.</span>#}
{#                                    </div>#}
{#                                    </p>#}
{#                                    <p>#}
{#                                    <div class="form-group has-error">#}
{#                                        <label class="control-label" for="inputError1">Input with error</label>#}
{#                                        <input type="text" class="form-control" id="inputError1">#}
{#                                    </div>#}
{#                                    </p>#}
{##}
{#                                </form>#}
{#							</div>#}
                            <form action="{% url 'mt:register' %}" method="post" id="register-view">
                                {% csrf_token %}
                                <div class="form-group has-feedback" id="email">
                                    <input type="text" class="form-control" aria-describedby="inputSuccess2Status"
                                           placeholder="邮箱" name="email">
                                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                    <p class="text"></p>
                                </div>

                                {#             密码#}
                                <div class="form-group has-feedback" id="password">
                                    <input type="password" class="form-control" aria-describedby="inputSuccess2Status"
                                           placeholder="密码" name="password">
                                    <span class="glyphicon glyphicon-ok form-control-feedback"
                                          aria-hidden="true"></span>
                                    <p class="help">
                                        格式：长度为6~12，且只能为数字、字母、下划线
                                    </p>
                                </div>

                                <div class="form-group has-feedback" id="password-d">
                                    <input type="password" class="form-control" aria-describedby="inputSuccess2Status"
                                           placeholder="密码">
                                    <span class="glyphicon glyphicon-ok form-control-feedback"
                                          aria-hidden="true"></span>
                                    <p class="help">
                                        格式：两次密码输入要保持一致!
                                    </p>
                                </div>


                                {#            名字#}
                                <div class="form-group has-feedback" id="name">
                                    <input type="text" class="form-control" aria-describedby="inputSuccess2Status"
                                           placeholder="名字(3~12)" name="name">
                                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                </div>
                                {#            手机#}
                                <div class="form-group has-feedback" id="phone">
                                    <input type="text" class="form-control" aria-describedby="inputSuccess2Status"
                                           placeholder="手机号" name="phone">
                                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                </div>

                                {#            <input type="submit" value="注册">#}
                                <button type="button" class="btn btn-primary" id="subButton"> 注册</button>
                            </form>
                        </div>


					</div>
				</div>
			</div>


		</div>
		<ul class="feeter">
			<li>
				Copyright©2009-2017 womai.com.hk All Rights Reserved 中粮海优（北京）有限公司版权所有<br />
				中粮海优（北京）有限公司 北京市朝阳区朝阳门南大街8号18F-09室<br />
				<p>
					<a href="#"><img src="{% static 'register/img/registerimg/beian.png' %}"/><b>京公网安备 11010102000458号</b></a>
				</p>
				<span>京ICP备 13003995号 营业执照（统一社会信用代码）91110000055590239L 食品经营许可证（社会信用代码）05559023-9</span>
				
			</li>
			<li class="color"></li>
		</ul>
	</body>
</html>